apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: dniel-se
spec:
  secretName: dniel-se-tls
  renewBefore: 360h # 15d
  commonName: '*.dniel.se'
  dnsNames:
  - '*.dniel.se'
  issuerRef:
    name: letsencrypt-prod-issuer
    kind: ClusterIssuer
  acme:
    config:
    - dns01:
        provider: dniel-se-dns
      domains:
      - '*.dniel.se'
