---
# Source: forwardauth/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: forwardauth
  labels:
    app: forwardauth
    chart: forwardauth-0.1.0
    release: forwardauth
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: forwardauth
    release: forwardauth
---
# Source: forwardauth/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forwardauth
  labels:
    app: forwardauth
    chart: forwardauth-0.1.0
    release: forwardauth
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forwardauth
      release: forwardauth
  template:
    metadata:
      labels:
        app: forwardauth
        release: forwardauth
    spec:
      containers:
        - name: forwardauth
          image: index.docker.io/dniel/forwardauth
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /config
          env:
            - name: JVM_OPTS
              value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
            - name: ENV
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi

      volumes:
        - name: config-volume
          configMap:
            name: forwardauth-config
