replicaCount: 1

image:
  repository: index.docker.io/dniel/forwardauth
  tag: latest
  pullPolicy: Always

# set logLevel to DEBUG, TEST, or PRODUCTION to control the verbosity of logs
# the container by default logs to STDOUT
logLevel: DEBUG

# Base configuration for OAuth2 and OIDC properties.
# domain, token endpoin, authorize url that needs to be set
# to enable the OAuth2 and oidc authentication workflows.
# If they are set here, they are injected as environment properties
# on the container instead of read from application.yaml
# It is also possible to set in application.yaml below.
domain: https://dniel.eu.auth0.com/
tokenEndpoint: https://dniel.eu.auth0.com/oauth/token
authorizeUrl: https://dniel.eu.auth0.com/authorize

# set the default application client-id and client-secret
# as environmentvariables to container and inject values from
# secrets instead of from application.yaml
default:
  scope: "profile openid email"

# Access ForwardAuth in two different configuration modes.
mode:
# Common host mode
# Forwardauth responds to all requests on a common address like auth.domain.com
# This is usefull if you have alot of application running and you want
# make it easy for people to navigate between applications.
# Will expose ForwardAuth on a subdomain like auth.example.test 
  host: true

# Path mode
# Forwardauth responds to all requests on path  yyy.xxx/oauth2
# on all registered routes/frontends. This is usefull when
# you want different cookie domains and limit SSO  navigation between different 
# subdomains and not use a common cookie domina for all applications. 
# Will expose the ForwardAuth application on a path like www.example.test/oauth2
  path: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hostname: auth.example.com
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
    traefik.ingress.kubernetes.io/priority: "99999"
  path: /oauth2

applicationYaml:
  domain: https://dniel.eu.auth0.com/
  token-endpoint: https://dniel.eu.auth0.com/oauth/token
  authorize-url: https://dniel.eu.auth0.com/authorize
  userinfo-endpoint: https://dniel.eu.auth0.com/userinfo
  logout-endpoint:  https://dniel.eu.auth0.com/v2/logout

  default:
    name: default
    audience: https://dniel.in
    scope: "profile openid email"
    redirect-uri: https://auth.dniel.in/signin
    token-cookie-domain: dniel.in
    claims:
    - sub
    - name
    - email

  apps:
  - name: grafana.dniel.in
    required-permissions:
    - read:grafana
  - name: kibana.dniel.in
    required-permissions:
    - read:kibana
  - name: traefik.dniel.in
    required-permissions:
    - read:traefik
  - name: whoami.dniel.in
    required-permissions:
    - read:whoami
  - name: www.dniel.in
    required-permissions:
    - read:www
    restricted-methods:
    - POST
    - PUT
    - PATCH
    - DELETE
  - name: spin.dniel.in
    required-permissions:
    - read:spinnaker
  - name: unifi.dniel.in
    required-permissions:
    - read:unifi
  - name: heimdall.dniel.in
    required-permissions:
    - read:heimdall
  - name: api-grahpql.dniel.in
    required-permissions:
    - read:graphql
  - name: api-posts.dniel.in
    required-permissions:
    - read:posts


resources:
  limits:
    memory: 512Mi
  requests:
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
