---
# Source: forwardauth/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: forwardauth
  labels:
    app: forwardauth
    chart: forwardauth-0.1.0
    release: forwardauth
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: forwardauth
    release: forwardauth
---
# Source: forwardauth/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forwardauth
  labels:
    app: forwardauth
    chart: forwardauth-0.1.0
    release: forwardauth
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forwardauth
      release: forwardauth
  template:
    metadata:
      labels:
        app: forwardauth
        release: forwardauth
    spec:
      containers:
        - name: forwardauth
          image: "index.docker.io/dniel/forwardauth:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /config
          env:
            - name: JVM_OPTS
              value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1          
            - name: ENV
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
          resources:
            limits:
              memory: 600Mi
            requests:
              memory: 600Mi
            
      volumes:
        - name: config-volume
          configMap:
            name: forwardauth-config
---
# Source: forwardauth/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: forwardauth
  labels:
    app: forwardauth
    chart: forwardauth-0.1.0
    release: forwardauth
    heritage: Tiller
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
    traefik.ingress.kubernetes.io/priority: "99999"
    
spec:
  rules:
  - http:
      paths:
        - backend:
            serviceName: forwardauth
            servicePort: http
          path: /oauth2
