apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-graphql
  name: api-graphql
  namespace: blogr
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: api-graphql
  template:
    metadata:
      labels:
        app: api-graphql
    spec:
      containers:
        - image: index.docker.io/dniel/api-graphql
          name: api-graphql
          ports:
            - containerPort: 8080
          livenessProbe:
            periodSeconds: 3
            tcpSocket:
              port: 8080
          readinessProbe:
            periodSeconds: 3
            httpGet:
              path: /system/health
              port: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: api-graphql
  namespace: blogr
spec:
  selector:
    app: api-graphql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
